In [ ]:
%tensorflow_version 1.x

TensorFlow 1.x selected.


In [ ]:
import tensorflow as tf
#print(tensorflow.__version__)

Tensorflow architecture works in three parts:

Preprocessing the data

Build the model

Train and estimate the model
# Tensor - multi dimensioanl array
Tensor goes in it flows through a list of operations, and then it comes out the other side.
It is called Tensorflow because it takes input as a multi-dimensional array, also known as tensors. 

In [ ]:
#TensorFlow provides a collection of workflows to develop and train models
#developed by an artificial intelligence researcher at Google named Francois Chollet

In [ ]:
#Types of precision floating-point.
"""
tf.float16 half-precision floating-point.
tf.float32 single bit floating-point.
tf.float64 double bit floating-point.
"""

'\ntf.float16 half-precision floating-point.\ntf.float32 single bit floating-point.\ntf.float64 double bit floating-point.\n'

In [ ]:
# Data type in Tensor
"""tf.float16`: 16-bit half-precision floating-point.
* `tf.bfloat16`: 16-bit truncated floating-point.
* `tf.complex64`: 64-bit single-precision complex.
* `tf.int8`: 8-bit signed integer.
* `tf.uint8`: 8-bit unsigned integer.
* `tf.qint8`: Quantized 8-bit signed integer.
* `tf.quint8`: Quantized 8-bit unsigned integer.
* `tf.bool`: Boolean.
* `tf.string`: String.
* `tf.resource`: Handle to a mutable resource.
* `tf.variant`: Values of arbitrary types."""
#float16,32,64;bfloat16,32,64,complex64,128,int8,16,32,64,uint8,16,32,64;qint8,16,32;quint8,16,32
#Signed integer is a 32-bit datum that encodes in the range[-2147483648 to 2147483647]. 
#Unsigned integer is a 32-bit datum that encodes a nonnegative integer in the range [0 to 4294967295]


'tf.float16`: 16-bit half-precision floating-point.\n* `tf.bfloat16`: 16-bit truncated floating-point.\n* `tf.complex64`: 64-bit single-precision complex.\n* `tf.int8`: 8-bit signed integer.\n* `tf.uint8`: 8-bit unsigned integer.\n* `tf.bool`: Boolean.\n* `tf.string`: String.\n* `tf.qint8`: Quantized 8-bit signed integer.\n* `tf.quint8`: Quantized 8-bit unsigned integer.\n* `tf.resource`: Handle to a mutable resource.\n* `tf.variant`: Values of arbitrary types.'

Three Type of Data in TF
1. Constant """Value remains Same e.g. a = 100"""
2. PlaceHolder
3. Variable 
# in Tensorflow variable allow us to add triangle parameter in the graph

In [ ]:
#Constant
"""A constant is a tensor whose value cannot be changed at all.
a takes a constant value 100 and hence the shape is None.
 You can declare any dimensional tensors by stacking up tensors on an existing tensor using the tf.
 stack function which can be seen from the example for nD Tensor."""

'A constant is a tensor whose value cannot be changed at all.\na takes a constant value 100 and hence the shape is None.\n You can declare any dimensional tensors by stacking up tensors on an existing tensor using the tf.\n stack function which can be seen from the example for nD Tensor.'

In [ ]:
#Variable
"""A variable is a tensor whose value is initialised and then typically changed as the program runs. 
In TF variables are manipulated by the tf.Variable class.
 The best way to create a variable is by calling the tf.get_variable function. 
This function requires you to specify the Variable’s name.
This name will be used by other replicas to access the same variable, 
as well as to name this variable’s value when check pointing and exporting models. 
tf.get_variable also allows us to reuse a previously created variable of the same name, making it easy to define 
models which reuse layers."""


In [ ]:
#Placeholder
"""Variables must be initialized before using. 
A placeholder is a node (same as a variable) 
whose value can be initialized in the future.
These nodes basically output the value assigned to them during runtime.
"""
# Tensorflow Placeholder is the promsise to provide the value later  

'Variables must be initialized before using. \nA placeholder is a node (same as a variable) \nwhose value can be initialized in the future.\nThese nodes basically output the value assigned to them during runtime.\n'

In [ ]:
hello = tf.constant("Hello Analyst")
hello

<tf.Tensor 'Const:0' shape=() dtype=string>

In [ ]:
hello # it will not give o/p
"""
IN TF everything should be run in session
"""

'\nIN TF everything should be run in session\n'

In [ ]:
#with tf.Session() as sess:
with tf.Session() as sess:
    output = sess.run(hello)
    print(output)

b'Hello Analyst'


In [ ]:
# Few Important Activation are function are below from Relu to tanh

In [ ]:
#Relu function
""" The rectified linear activation function or ReLU for short is a piecewise linear function that will output the input directly if it is positive,
 otherwise, it will output zero.
 Relu activates node if input is above certain quantity
 if input is 0 then O/p is 0. but when input raises above a certain threshold, 
 it has a linear relationship with dependent variable
  Mathematical representation:
            0 if x<=0
  f(x) = {
            x if x>0
"""

In [ ]:
import numpy as np
def relu_a(x):
  
  return np.maximum(0,x)
#relu_a()
a =[-4,-2,0,7999]
print (relu_a(a))


[   0    0    0 7999]


In [ ]:
#Softmax
"""
The softmax function is a function that turns a vector of K real values into a vector of K real values that sum to 1. 
The input values can be any type of numbers, but the softmax transforms them into values between 0 and 1, 
so that they can be interpreted as probabilities. 
If one of the inputs is small or negative, the softmax turns it into a small probability,  near to 0
and if an input is large, then it turns it into a large probability near to 1, but it will always remain between 0 and 1.
"""
#when to use softmax function
"""
When we have 4-5 classes of output that time softmax is useful cause it gives probabilities of it.
Also useful for finding out the class whose probability is maximum"""
"""
Softmax function output layers are classifiers
Mathematical Notation:
sigma(z)j = e^zj / summation of k=1 to K of e^zk ..... for j = 1.....k

Softmax is better to use when we have classes more than 2"""


'\nSoftmax function output layers are classifiers\nMathematical Notation:\nsigma(z)j = e^zj / summation of k=1 to K of e^zk ..... for j = 1.....k\n\nSoftmax is better to use when we have classes more than 2'

In [ ]:
#Scores = [12,8,.3,-10,10]
Scores = [-50,-55]
import numpy as np
def softmax(x):
    return np.exp(x)/np.sum(np.exp(x),axis  = 0)
print(softmax(Scores))
sum(softmax(Scores))

[0.99330715 0.00669285]


1.0

In [ ]:
#Linear or Identity
"""A Linear transform is basically the identity function, where the dependent 
varible has a 
direct proportional relationship with the independent variable.
i.e. In Practical terms it means the function passes the signal through
 unchanged
Mathematical Representation : f(x) = x
"""

In [ ]:
# Threshold Function or unit step
"""O/p of unit step function is either 1 or 0.
Depends on threshold value defined by the user
Mathematical Representation:
          0 if 0>x
f(x) = {
          1 if x>=0
"""

In [ ]:
# Sigmoid Function
"""The sigmoid activation function, also called the logistic function.
Traditionally it was popular as a activation function for neural networks. 
The input to the function is transformed into a value between 0 to 1. 
Inputs that are much larger than 1.0 are transformed to the value 1.0,
 similarly, values much smaller than 0.0 are snapped to 0.0.
"""
"""
Sigmiod Function is the machine that converts independent variables
most of the o/p will be very close to 0 or 1
Mathematical Representation
f(x) = 1/ 1+e ^(-B*x) #B is bita 
 """

In [ ]:
import numpy as np
#from tf import sigmoid_
def sigmoid_(a):
  return 1/(1+np.exp(-a))
     

In [ ]:
#sigmoid_
#a = [1,2,4,0,5,6,7]
a = [1,2,100,-1,-2,-100]
for i in a:
  print (sigmoid_(i))

0.7310585786300049
0.8807970779778823
1.0
0.2689414213699951
0.11920292202211755
3.7200759760208356e-44


In [ ]:
#Tanh
"""is A hyperbolic trignometric function
Tanh is range between -1 to 1.
it deals with -ve number easily.
Mathematical representation
f(x) =. tanh(x)
"""

In [ ]:
a = (e^a - e^-a)/e^a + e^-a
tanh(a)

NameError: ignored

In [ ]:
#RaggedTensor
"""
A `RaggedTensor` is a tensor with one or more *ragged dimensions*, which are
dimensions whose slices may have different lengths.
The outermost dimension of a `RaggedTensor` is always uniform,
since it consists of a single slice (and so there is no possibility for
differing slice lengths).
The total number of dimensions in a `RaggedTensor` is called its *rank*,
and the number of ragged dimensions in a `RaggedTensor` is called its
*ragged-rank*."""

'\nA `RaggedTensor` is a tensor with one or more *ragged dimensions*, which are\ndimensions whose slices may have different lengths.\nThe outermost dimension of a `RaggedTensor` is always uniform,\nsince it consists of a single slice (and so there is no possibility for\ndiffering slice lengths).\nThe total number of dimensions in a `RaggedTensor` is called its *rank*,\nand the number of ragged dimensions in a `RaggedTensor` is called its\n*ragged-rank*.'

In [ ]:
#Calculations using TF
a1 = tf.constant([1, 2, 3])
a2 = tf.constant([3, 4, 5])
a3 = a1 + a2 
with tf.Session() as session:
  print(session.run(a3))


[4 6 8]


In [ ]:
a4 = a1 - a2
with tf.Session() as session:
  print(session.run(a4))

[-2 -2 -2]


In [ ]:
a5 = a1 * a2 # (tf supports primitive operators)

with tf.Session() as session:
  print(session.run(a5))
   

[ 3  8 15]


In [ ]:
a6 = a1/a2
with tf.Session() as session:
  print(a6.eval()) #eval() can be used instead of session.run() to compute the results of a particular variable.
  

[0.33333333 0.5        0.6       ]


In [ ]:
In TF We can perform all necessary mathematical operation required for matrix calculation.